sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_f5ba61e8c422_key -iv $encrypted_f5ba61e8c422_iv -in gcloud-key.json.enc -out gcloud-key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gcloud-key.json
  - gcloud config set project complex-k8s-293514
  - gcloud config set compute/zone europe-west1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sturs23/client-tests -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sturs23/client-tests npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
